# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Telegram Profiler

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Create virtual environment
      run: |
        python -m venv .venv
        .venv/Scripts/activate
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build flet app
      run: |
        flet pack TelegramProfiler.py --icon "favicon.ico" --company-name "labarjni" --product-name "Telegram Profiler" --copyright "Copyright (c) 2024 labarjni"
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: TelegramProfiler
        path: dist/TelegramProfiler.exe
