# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Telegram Profiler

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build flet app
      run: |
        flet pack TelegramProfiler.py --icon "favicon.ico" --company-name "labarjni" --product-name "Telegram Profiler" --copyright "Copyright (c) 2024 labarjni"
    - run: mkdir staging && cp dist/TelegramProfiler.exe staging
    - uses: actions/upload-artifact@v1
